schema: atomic
id: 178c34fc-c295-4b6d-a73d-f5f8ae905169
name: Add Password to Azure AD Application
metadata:
  creationDate: '2021-08-05'
  modificationDate: '2021-09-08'
  description: |
    A threat actor might want to add a password to an Azure AD application for persistence purposes via Microsoft Graph APIs and the right permissions.
  contributors:
    - Roberto Rodriguez @Cyb3rWard0g
    - MSTIC R&D
  mitreAttack:
    - technique: T1098.001
      tactics:
        - TA0003
authorization:
  - resource: https://graph.microsoft.com/
    permissionsType: application
    permissions:
      - Application.ReadWrite.All
execution:
  type: ScriptModule
  platform: Azure
  executor: PowerShell
  module:
    name: CloudKatanaAbilities
    version: 1.0
    function: Add-CKAzADAppPassword
  parameters:
    displayName:
      type: string
      description: The name (displayName) of the new Azure AD Application.
      required: true
    appObjectId:
      type: string
      description: The object id (id) of the Azure AD application.
      required: true