schema: atomic
id: c0d902ba-e4a9-418e-93fe-c3b0c0df65db
name: Update Azure AD Application Required Resource Access
metadata:
  creationDate: '2021-08-05'
  modificationDate: '2021-09-08'
  description: |
    A threat actor might want to update the required resource access property of an Azure AD application via Microsoft Graph APIs and the right permissions. The requiredResourceAccess property of an application specifies resources that the application requires access to and the set of OAuth permission scopes (delegated) and application roles (application) that it needs under each of those resources. This pre-configuration of required resource access drives the consent experience. This does not grant permissions consent.
  contributors:
    - Roberto Rodriguez @Cyb3rWard0g
    - MSTIC R&D
  mitreAttack:
    - technique: T1098.002
      tactics:
        - TA0003
authorization:
  - resource: https://graph.microsoft.com/
    permissionsType: application
    permissions:
      - Application.ReadWrite.All
execution:
  type: ScriptModule
  platform: Azure
  executor: PowerShell
  module:
    name: CloudKatanaAbilities
    version: 1.0
    function: Update-CKAzADAppReqRscAccess
  parameters:
    appId:
      type: string
      description: The ID (client_id) of the application we want to update.
      required: true
    resourceName:
      type: string
      description: Name of the resource the application requires access to. This is the service principal name associated with the resource (i.e. Microsoft Graph).
      required: true
    permissionType:
      type: string
      description: Type of permissions required. It could of type Delegated or Application.
      required: true
    permissions:
      type: array
      description: An array of required permissions for the application.
      required: true