schema: atomic
id: 54169cc7-baf0-40b0-8431-89add22356fb
name: Add New Owner to Azure AD Application
metadata:
  creationDate: '2021-08-05'
  modificationDate: '2021-09-08'
  description: |
    A threat actor might want to add an owner to an Azure AD application via Microsoft Graph APIs and the right permissions.
  contributors:
    - Roberto Rodriguez @Cyb3rWard0g
    - MSTIC R&D
  mitreAttack:
    - technique: T1098.001
      tactics:
        - TA0003
authorization:
  - resource: https://graph.microsoft.com/
    permissionsType: application
    permissions:
      - Application.ReadWrite.All
      - Directory.Read.All
execution:
  type: ScriptModule
  platform: Azure
  executor: PowerShell
  module:
    name: CloudKatanaAbilities
    version: 1.0
    function: Add-CKOwnerToAzADApp
  parameters:
    appObjectId:
      type: string
      description: The object id (id) of the Azure AD application
      required: true
    directoryObjectId:
      type: string
      description: Identifier of the directory object to be assigned as owner.
      required: true