title: New-CKAzADApplication
id: ea4ea3b0-b022-4f36-b111-9be342e00240
creationDate: '2021-08-05'
modificationDate: '2021-09-08'
description: |
  A threat actor might want to register a new Azure AD application for persistence purposes.
contributors:
- Roberto Rodriguez @Cyb3rWard0g
- MSTIC R&D
ctiReferences:
attackMappings:
- technique: T1136.003
  tactics:
  - TA0003
platform: Azure
resource:
  url: https://graph.microsoft.com/
  authorization:
    permissionsType: application
    permissions:
    - Application.ReadWrite.All
parameters:
  displayName:
    type: string
    description: The name (displayName) of the new Azure AD Application.
    required: true
  nativeApp:
    type: switch
    description: Switch to register an application which can be installed on a user's device or computer.
    required: false
  signInAudience:
    type: string
    description: Specifies the Microsoft accounts that are supported for the current application. The possible values are AzureADMyOrg, AzureADMultipleOrgs, AzureADandPersonalMicrosoftAccount (default), and PersonalMicrosoftAccount
    defaultValue: AzureADMyOrg
    required: false
  identifierUris:
    type: string
    description: Space-separated unique URIs that Azure AD can use for this app.
    required: false
  replyUrls:
    type: string
    description: Space-separated URIs to which Azure AD will redirect in response to an OAuth 2.0 request. The value does not need to be a physical endpoint, but must be a valid URI.
    required: false
  useV2AccessTokens:
    type: switch
    description: Switch to set application to use V2 access tokens.
    required: false
  accessToken:
    type: string
    description: Access token used to access the API.
    required: true
scripts:
  - kind: PowerShell
    module: CloudKatana
    scriptPath: durableApp\Modules\CloudKatana\persistence\New-CKAzADApplication.ps1
