schema: atomic
id: 3d4bbcfa-e252-4bc2-ab0d-d8cfc78240a2
name: Get Azure AD Application Metadata
metadata:
  creationDate: '2021-08-05'
  modificationDate: '2021-09-08'
  description: |
    A threat actor might want to get metadata from Azure AD Applications via Microsoft Graph APIs and the right permissions.
  contributors:
    - Roberto Rodriguez @Cyb3rWard0g
    - MSTIC R&D
  mitreAttack:
    - technique: T1087.004
      tactics:
        - TA0007
authorization:
  - resource: https://graph.microsoft.com/
    permissionsType: application
    permissions:
      - Application.Read.All
execution:
  type: ScriptModule
  platform: Azure
  executor: PowerShell
  module:
    name: CloudKatanaAbilities
    version: 1.0
    function: Get-CKAzADApplication
  parameters:
    appObjectId:
      type: string
      description: The object id (id) of the Azure AD application.
      required: false
    selectFields:
      type: string
      description: Specific properties/columns to return from objects using the $select query parameter.
      required: false
    filter:
      type: string
      description: Filter results by using the $filter query parameter to retrieve just a subset of a collection.
      required: false
    pageSize:
      type: int
      description: Specific number of objects to return per page using the $top query parameter. $top sets the page size of results.
      required: false