title: createAdApplication
id: ea4ea3b0-b022-4f36-b111-9be342e00240
creationDate: '2021-08-05'
modificationDate: '2021-08-05'
description: |
  A threat actor might want to register a new Azure AD application for persistence purposes.
contributors:
- Roberto Rodriguez @Cyb3rWard0g
- MSTIC R&D
ctiReferences:
- https://msrc-blog.microsoft.com/2020/12/21/december-21st-2020-solorigate-resource-center/
attackMappings:
- technique: T1136.003
  tactics:
  - TA0003
platform: Azure
resource:
  url: https://graph.microsoft.com/
  authorization:
    permissionsType: application
    permissions:
    - Application.ReadWrite.All
parameters:
  displayName:
    type: string
    description: The display name of the application.
  accessToken:
    type: string
    description: Access token with the right permissions to access and interact with the Azure resource.
executor:
  type: PowerShell
  scriptContent: |
    $body = @{ 
      displayName = "$displayName"
    }
    $response = Invoke-MSGraph -HttpMethod "Post" -Resource "applications" -AccessToken $accessToken -Body $body
    $response
output:
  response:
    type: object