title: getAdApplication
id: 3d4bbcfa-e252-4bc2-ab0d-d8cfc78240a2
creationDate: '2021-08-05'
modificationDate: '2021-08-05'
description: |
  A threat actor might want to get metadata from a specific Azure AD Application.
contributors:
- Roberto Rodriguez @Cyb3rWard0g
- MSTIC R&D
ctiReferences:
- https://msrc-blog.microsoft.com/2020/12/21/december-21st-2020-solorigate-resource-center/
attackMappings:
- technique: T1087.004
  tactics:
  - TA0007
platform: Azure
resource:
  url: https://graph.microsoft.com/
  authorization:
    permissionsType: application
    permissions:
    - Application.Read.All
parameters:
  appObjectId:
    type: string
    description: The Azure AD application object id.
  accessToken:
    type: string
    description: Access token with the right permissions to access and interact with the Azure resource.
executor:
  type: PowerShell
  scriptContent: |
    $response = Invoke-MSGraph -Resource "applications/$appObjectId" -AccessToken $accessToken
    $response
output:
  response:
    type: object