title: Get-CKAzADApplication
id: 3d4bbcfa-e252-4bc2-ab0d-d8cfc78240a2
creationDate: '2021-08-05'
modificationDate: '2021-09-08'
description: |
  A threat actor might want to get metadata from Azure AD Applications.
contributors:
- Roberto Rodriguez @Cyb3rWard0g
- MSTIC R&D
ctiReferences:
attackMappings:
- technique: T1087.004
  tactics:
  - TA0007
platform: Azure
resource:
  url: https://graph.microsoft.com/
  authorization:
    permissionsType: application
    permissions:
    - Application.Read.All
parameters:
  appObjectId:
    type: string
    description: The object id (id) of the Azure AD application.
    required: false
  selectFields:
    type: string
    description: Specific properties/columns to return from objects using the $select query parameter.
    required: false
  filter:
    type: string
    description: Filter results by using the $filter query parameter to retrieve just a subset of a collection.
    required: false
  pageSize:
    type: int
    description: Specific number of objects to return per page using the $top query parameter. $top sets the page size of results.
    required: false
  accessToken:
    type: string
    description: Access token used to access the API.
    required: true
scripts:
  - kind: PowerShell
    module: CloudKatana
    scriptPath: durableApp\Modules\CloudKatana\discovery\Get-CKAzADApplication.ps1